spring:
  datasource:
    url: jdbc:mysql://root:NmVkkfIbISdPhUlvKudM@containers-us-west-42.railway.app:5462/railway
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate # Create se for rodar pela primeira vez
      dialect: org.hibernate.dialect.MySQLDialect

